name: ctrl_env
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  - pip:
    # common libs
    - tqdm
    - numpy
    - scipy
    - matplotlib
    # graphics libs
    - meshio
    - open3d
    - meshcat
    - meshcat-shapes
    - pyvista
    - pyquaternion
    - opencv-python
    # sims
    - pin
    - pin-pink
    - qpsolvers[open_source_solvers]
